[
    {
        "aws": {
            "awslogs": {
                "logGroup": "/aws/rds/instance/datadog/postgresql",
                "logStream": "datadog.0",
                "owner": "123456789012"
            },
            "function_version": 0,
            "invoked_function_arn": "invoked_function_arn"
        },
        "ddsource": "cloudwatch",
        "ddsourcecategory": "aws",
        "ddtags": "forwardername:function_name,forwarder_memorysize:10,forwarder_version:<redacted>,test_tag_key:test_tag_value",
        "host": "/aws/rds/instance/datadog/postgresql",
        "id": "31953106606966983378809025079804211143289615424298221568",
        "message": "2021-01-02 03:04:05 UTC::@:[5306]:LOG:  database system is ready to accept connections",
        "service": "cloudwatch",
        "timestamp": 1609556645000
    }
]
